version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
    ports:
      - "5433:5432"
    networks:
      - app_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
#      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql

  redis:
    image: redis:7
    ports:
      - "6380:6379"
    networks:
      - app_network

  soundhub-api:
    build:
      dockerfile: ./docker/Dockerfile
      context: ..
    restart: always
    environment:
      spring.redis.host: redis
      token.signing.expirationInMs: 3600000

      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_REDIS_HOST: redis
    ports:
      - "8080:8080"
      - "8888:8888"
    depends_on:
      - db
      - redis
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network: